server:
  port: 9002
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create
  application:
    name: order-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka